# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/xavier/www/mon_arduino/python_avec_arduino/mes_pyQt/tuto_pyqt_pyserial_terminal_envoi_chaine_sliderx5/tuto_pyqt_pyserial_terminal_envoi_chaine_sliderx5.ui'
#
# Created: Fri Mar  8 15:55:38 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(626, 358)
        self.comboBoxPort = QtGui.QComboBox(Form)
        self.comboBoxPort.setGeometry(QtCore.QRect(10, 20, 121, 24))
        self.comboBoxPort.setEditable(True)
        self.comboBoxPort.setObjectName(_fromUtf8("comboBoxPort"))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.labelPort = QtGui.QLabel(Form)
        self.labelPort.setGeometry(QtCore.QRect(10, 5, 101, 16))
        self.labelPort.setObjectName(_fromUtf8("labelPort"))
        self.comboBoxDebit = QtGui.QComboBox(Form)
        self.comboBoxDebit.setGeometry(QtCore.QRect(10, 65, 121, 24))
        self.comboBoxDebit.setObjectName(_fromUtf8("comboBoxDebit"))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.labelDebit = QtGui.QLabel(Form)
        self.labelDebit.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.labelDebit.setObjectName(_fromUtf8("labelDebit"))
        self.pushButtonInitSerial = QtGui.QPushButton(Form)
        self.pushButtonInitSerial.setGeometry(QtCore.QRect(135, 10, 41, 81))
        self.pushButtonInitSerial.setObjectName(_fromUtf8("pushButtonInitSerial"))
        self.textEditReception = QtGui.QTextEdit(Form)
        self.textEditReception.setGeometry(QtCore.QRect(10, 215, 171, 136))
        self.textEditReception.setStyleSheet(_fromUtf8("background-color: rgb(244, 255, 190);"))
        self.textEditReception.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEditReception.setObjectName(_fromUtf8("textEditReception"))
        self.labelReception = QtGui.QLabel(Form)
        self.labelReception.setGeometry(QtCore.QRect(10, 195, 191, 16))
        self.labelReception.setObjectName(_fromUtf8("labelReception"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 90, 166, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 185, 166, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.labelChaineEnvoi = QtGui.QLabel(Form)
        self.labelChaineEnvoi.setGeometry(QtCore.QRect(10, 105, 121, 16))
        self.labelChaineEnvoi.setObjectName(_fromUtf8("labelChaineEnvoi"))
        self.lineEditChaineEnvoi = QtGui.QLineEdit(Form)
        self.lineEditChaineEnvoi.setGeometry(QtCore.QRect(10, 120, 166, 23))
        self.lineEditChaineEnvoi.setObjectName(_fromUtf8("lineEditChaineEnvoi"))
        self.comboBoxFinLigne = QtGui.QComboBox(Form)
        self.comboBoxFinLigne.setGeometry(QtCore.QRect(10, 160, 121, 24))
        self.comboBoxFinLigne.setObjectName(_fromUtf8("comboBoxFinLigne"))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.labelFinLigne = QtGui.QLabel(Form)
        self.labelFinLigne.setGeometry(QtCore.QRect(10, 145, 71, 16))
        self.labelFinLigne.setObjectName(_fromUtf8("labelFinLigne"))
        self.pushButtonEnvoi = QtGui.QPushButton(Form)
        self.pushButtonEnvoi.setGeometry(QtCore.QRect(135, 145, 41, 41))
        self.pushButtonEnvoi.setObjectName(_fromUtf8("pushButtonEnvoi"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(180, 5, 16, 346))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.lineEditSlider_1 = QtGui.QLineEdit(Form)
        self.lineEditSlider_1.setGeometry(QtCore.QRect(220, 30, 166, 23))
        self.lineEditSlider_1.setObjectName(_fromUtf8("lineEditSlider_1"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(195, 250, 421, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.labelTraceEnvoiSerie = QtGui.QLabel(Form)
        self.labelTraceEnvoiSerie.setGeometry(QtCore.QRect(195, 260, 191, 16))
        self.labelTraceEnvoiSerie.setObjectName(_fromUtf8("labelTraceEnvoiSerie"))
        self.textEditTraceEnvoiSerie = QtGui.QTextEdit(Form)
        self.textEditTraceEnvoiSerie.setGeometry(QtCore.QRect(195, 275, 426, 76))
        self.textEditTraceEnvoiSerie.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(170, 255, 255);"))
        self.textEditTraceEnvoiSerie.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEditTraceEnvoiSerie.setObjectName(_fromUtf8("textEditTraceEnvoiSerie"))
        self.lcdNumber_1 = QtGui.QLCDNumber(Form)
        self.lcdNumber_1.setGeometry(QtCore.QRect(500, 10, 91, 36))
        self.lcdNumber_1.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.lcdNumber_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_1.setProperty("intValue", 90)
        self.lcdNumber_1.setObjectName(_fromUtf8("lcdNumber_1"))
        self.horizontalSlider_1 = QtGui.QSlider(Form)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(220, 10, 271, 19))
        self.horizontalSlider_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_1.setMaximum(180)
        self.horizontalSlider_1.setSingleStep(5)
        self.horizontalSlider_1.setPageStep(25)
        self.horizontalSlider_1.setProperty("value", 90)
        self.horizontalSlider_1.setSliderPosition(90)
        self.horizontalSlider_1.setTracking(True)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setInvertedAppearance(False)
        self.horizontalSlider_1.setInvertedControls(False)
        self.horizontalSlider_1.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider_1.setTickInterval(10)
        self.horizontalSlider_1.setObjectName(_fromUtf8("horizontalSlider_1"))
        self.horizontalSlider_2 = QtGui.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(220, 60, 271, 19))
        self.horizontalSlider_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_2.setMaximum(180)
        self.horizontalSlider_2.setSingleStep(5)
        self.horizontalSlider_2.setPageStep(25)
        self.horizontalSlider_2.setProperty("value", 120)
        self.horizontalSlider_2.setSliderPosition(120)
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setInvertedControls(False)
        self.horizontalSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider_2.setTickInterval(10)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.lcdNumber_2 = QtGui.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(500, 60, 91, 36))
        self.lcdNumber_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("intValue", 120)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lineEditSlider_2 = QtGui.QLineEdit(Form)
        self.lineEditSlider_2.setGeometry(QtCore.QRect(220, 80, 166, 23))
        self.lineEditSlider_2.setObjectName(_fromUtf8("lineEditSlider_2"))
        self.horizontalSlider_3 = QtGui.QSlider(Form)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(220, 110, 271, 19))
        self.horizontalSlider_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_3.setMaximum(180)
        self.horizontalSlider_3.setSingleStep(5)
        self.horizontalSlider_3.setPageStep(25)
        self.horizontalSlider_3.setProperty("value", 0)
        self.horizontalSlider_3.setSliderPosition(0)
        self.horizontalSlider_3.setTracking(True)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider_3.setTickInterval(10)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.lcdNumber_3 = QtGui.QLCDNumber(Form)
        self.lcdNumber_3.setGeometry(QtCore.QRect(500, 110, 91, 36))
        self.lcdNumber_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.lcdNumber_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_3.setProperty("intValue", 0)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.lineEditSlider_3 = QtGui.QLineEdit(Form)
        self.lineEditSlider_3.setGeometry(QtCore.QRect(220, 130, 166, 23))
        self.lineEditSlider_3.setObjectName(_fromUtf8("lineEditSlider_3"))
        self.horizontalSlider_4 = QtGui.QSlider(Form)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(220, 160, 271, 19))
        self.horizontalSlider_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_4.setMaximum(180)
        self.horizontalSlider_4.setSingleStep(5)
        self.horizontalSlider_4.setPageStep(25)
        self.horizontalSlider_4.setProperty("value", 0)
        self.horizontalSlider_4.setSliderPosition(0)
        self.horizontalSlider_4.setTracking(True)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setInvertedAppearance(False)
        self.horizontalSlider_4.setInvertedControls(False)
        self.horizontalSlider_4.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider_4.setTickInterval(10)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.lcdNumber_4 = QtGui.QLCDNumber(Form)
        self.lcdNumber_4.setGeometry(QtCore.QRect(500, 160, 91, 36))
        self.lcdNumber_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.lcdNumber_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_4.setProperty("intValue", 0)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.lineEditSlider_4 = QtGui.QLineEdit(Form)
        self.lineEditSlider_4.setGeometry(QtCore.QRect(220, 180, 166, 23))
        self.lineEditSlider_4.setObjectName(_fromUtf8("lineEditSlider_4"))
        self.horizontalSlider_5 = QtGui.QSlider(Form)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(220, 210, 271, 19))
        self.horizontalSlider_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_5.setMaximum(180)
        self.horizontalSlider_5.setSingleStep(5)
        self.horizontalSlider_5.setPageStep(25)
        self.horizontalSlider_5.setProperty("value", 10)
        self.horizontalSlider_5.setSliderPosition(10)
        self.horizontalSlider_5.setTracking(True)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setInvertedAppearance(False)
        self.horizontalSlider_5.setInvertedControls(False)
        self.horizontalSlider_5.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider_5.setTickInterval(10)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.lcdNumber_5 = QtGui.QLCDNumber(Form)
        self.lcdNumber_5.setGeometry(QtCore.QRect(500, 210, 91, 36))
        self.lcdNumber_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.lcdNumber_5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("intValue", 10)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.lineEditSlider_5 = QtGui.QLineEdit(Form)
        self.lineEditSlider_5.setGeometry(QtCore.QRect(220, 230, 166, 23))
        self.lineEditSlider_5.setObjectName(_fromUtf8("lineEditSlider_5"))

        self.retranslateUi(Form)
        self.comboBoxFinLigne.setCurrentIndex(1)
        QtCore.QObject.connect(self.horizontalSlider_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_1.display)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_2.display)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_3.display)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_4.display)
        QtCore.QObject.connect(self.horizontalSlider_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_5.display)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "PyQt + PySerial : Terminal Série + Slider x5 envoi chaine", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPort.setItemText(0, QtGui.QApplication.translate("Form", "/dev/ttyACM0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPort.setItemText(1, QtGui.QApplication.translate("Form", "/dev/ttyACM1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPort.setItemText(2, QtGui.QApplication.translate("Form", "/dev/ttyUSB0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPort.setItemText(3, QtGui.QApplication.translate("Form", "/dev/ttyUSB1", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPort.setText(QtGui.QApplication.translate("Form", "Port Série :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(0, QtGui.QApplication.translate("Form", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(1, QtGui.QApplication.translate("Form", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(2, QtGui.QApplication.translate("Form", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(3, QtGui.QApplication.translate("Form", "28800", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(4, QtGui.QApplication.translate("Form", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(5, QtGui.QApplication.translate("Form", "14400", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(6, QtGui.QApplication.translate("Form", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDebit.setItemText(7, QtGui.QApplication.translate("Form", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDebit.setText(QtGui.QApplication.translate("Form", "Débit Série (bauds) :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonInitSerial.setText(QtGui.QApplication.translate("Form", "Init", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReception.setText(QtGui.QApplication.translate("Form", "Réception sur le port série : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChaineEnvoi.setText(QtGui.QApplication.translate("Form", "Chaîne à envoyer :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFinLigne.setItemText(0, QtGui.QApplication.translate("Form", "Rien", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFinLigne.setItemText(1, QtGui.QApplication.translate("Form", "Saut de ligne (\\n = LF)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFinLigne.setItemText(2, QtGui.QApplication.translate("Form", "Retour Chariot (\\r = CR)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFinLigne.setItemText(3, QtGui.QApplication.translate("Form", "Les 2 (LF + CR)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFinLigne.setText(QtGui.QApplication.translate("Form", "Fin de ligne :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEnvoi.setText(QtGui.QApplication.translate("Form", "Envoi", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSlider_1.setText(QtGui.QApplication.translate("Form", "servoTo(0,", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTraceEnvoiSerie.setText(QtGui.QApplication.translate("Form", "Envoi sur le port série : ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSlider_2.setText(QtGui.QApplication.translate("Form", "servoTo(1,", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSlider_3.setText(QtGui.QApplication.translate("Form", "servoTo(2,", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSlider_4.setText(QtGui.QApplication.translate("Form", "servoTo(3,", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSlider_5.setText(QtGui.QApplication.translate("Form", "servoTo(4,", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

